### ISSUE TITLE
the Script is good but i need to remove ""Hi there owner of { business's name }"."

### ISSUE THREAD

**Issue by TamerElShazly** [zorridge/whatsapp-auto-sender#1]
i need to remove ""Hi there owner of { business's name }"." from the beginning of my customized messages

**Comment by zorridge** [comment]
You can clone the repo and in `app.py` remove line 63 and 65, then for line 66 change `messageSent` to `message` i.e. `sendWhatsappMessage(number, message, delay, True, 5)`

Let me know if you need a new executable release instead. Cheers!
